### ISSUE TITLE
Where is chapelhill.txt?

### ISSUE THREAD

**Issue by Clementevigliotti92** [timthirion/ezw#1]
Hi, I don't found the data set "chapelhill.txt", where is it?

**Comment by timthirion** [comment]
I don't have the data set anymore but the format isn't difficult to create. It's simply two integer values specifying the `width` and `height` of the data followed by `width*height` floating point values.

So, for a 512x512 image, the file looks like:
`512
512
3.0 1.2 3.4 5.4 ...
`
