### ISSUE TITLE
Which paper did you reference

### ISSUE THREAD

**Issue by Dwgjjdxq** [timthirion/ezw#2]
Hello Tim,

I want to use your source code about the "Embedded zerotree wavelet compression" for the mesh simplification compression. So cloud you share the reference paper? I

**Comment by timthirion** [comment]
I don't recall as it's been over 10 years. I recommend just doing a search for it.

**Comment by Dwgjjdxq** [comment]
Ok!

Thank you for your reply.

Best regards,
Andrew
E-mail: dwgjjdxq@gmail.com

2017-03-16 22:12 GMT+08:00 Tim Thirion <notifications@github.com>:
